# v2 syntax
version: '2'

# Named volumes
volumes:
  accordous-novo-mysql-data:
    driver: local
  accordous-novo-redis-data:
    driver: local

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: accordous-novo-nginx-proxy
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${DOCKER_SOCKET}:/tmp/docker.sock:ro
    links:
      - backend
      - frontend

  composer:
    restart: 'no'
    image: composer:1.9.2
    container_name: accordous-novo-composer
    command: install --ignore-platform-reqs
    volumes:
      - ./apiato/:/app

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: accordous-novo-mysql
    volumes:
      - accordous-novo-mysql-data:/var/lib/mysql
      - ./apiato/database/:/docker-entrypoint-initdb.d
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  memcached:
    image: 'bitnami/memcached:latest'
    container_name: accordous-novo-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_MAX_CONNECTIONS=1024

  # Redis
  redis:
    image: redis:4.0
    container_name: accordous-novo-redis
    command: --appendonly yes
    volumes:
      - accordous-novo-redis-data:/data

  # BACKEND
  backend:
    image: ambientum/php:7.2-nginx
    container_name: accordous-novo-backend
    volumes:
      - ./apiato/:/var/www/app
    environment:
      - VIRTUAL_HOST=backend.${HOST_NAME}
      - APP_URL=http://${HOST_NAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=backend
    links:
      - composer
      - mysql
      - memcached
      - redis
      - queue

  # FRONTEND
  frontend:
    image: ambientum/php:7.2-nginx
    container_name: accordous-novo-frontend
    volumes:
      - ./apiato/:/var/www/app
    environment:
      - VIRTUAL_HOST=${HOST_NAME}
      - APP_URL=http://${HOST_NAME}
      - APP_ENV=frontend
    links:
      - composer
      - memcached
      - redis
      - backend

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: accordous-novo-queue
    command: php artisan queue:listen
    volumes:
      - ./apiato/:/var/www/app
    environment:
      - APP_URL=http://${HOST_NAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=queue
    links:
      - mysql
      - memcached
      - redis
